print("Hello python")
print('Hello words')
print("""Hello
         words
         tops""")
print("python \" Hello")
print('Hello \' words')
print("Hello ' words")
print('Hello " words')
print("Hello \\words")
print("abc \txyz")
print("abc\bxyz")
print("abc\nxyz")
print("python","java","php",sep="|")
print("python",end="")
print("php")
print('Hello \\\' words')
print(r"python is \" opps lang")
name =input("Enter name:")
print(name)
a=int(input("Enter number1: "))
b=int(input("Enter number2: "))
print(a+b)
a=100
b=int(a)
print(type(a))
print(type(b))
name="Tops technologies pvt ltd ".split()
print(name)
fname="mayuri"
lname="chaudhari"
print("my name is {} and my surname is {}".format(fname,lname))
print(f"my name is {fname} and surname is {lname}")
